### PR TITLE
Fix: Fix Module When `var.enabled=false`

### PR DESCRIPTION
**Pull request by korenyoni**
## what
- Fix module when `var.enabled`=`false`.
- Expand variable documentation (`client_sasl_*_enabled` and `client_tls_auth_enabled` conflicting).
- Add Terratest for when module is disabled.
- Misc: move BridgeCrew exceptions to top of resource.

## why

- Following #46 , this module does not work when `var.enabled`=`false`.
- The former issue would have been caught if a test existed when `var.enabled`=`false`.

## references
* #46

### CODE REVIEW

**Review by max-lobur — APPROVED** [review]

**Review by nitrocode — APPROVED** [review]
🚀

**Comment by korenyoni** [comment]
I initially put in the `no-release` label because I wanted to consolidate this PR alongside https://github.com/cloudposse/terraform-aws-msk-apache-kafka-cluster/pull/45 — but that PR needs more work and this is a hotfix

**Pull request merged**
