### PR TITLE
Typo: Duplicated description text

### PR DESCRIPTION
**Pull request by hawkesnc**
## what
- The `number_of_broker_nodes` in the example has duplicated text.

## why
- Correctness

### CODE REVIEW

**Review by woz5999 — DISMISSED** [review]

**Comment by hawkesnc** [comment]
Would someone with write access be able to approve/merge this? Thanks!

**Comment by woz5999** [comment]
@hawkesnc the automated tests are failing, blocking the merge

**Review by htplbc — APPROVED** [review]

**Review by htplbc — DISMISSED** [review]

**Review by maximmi — APPROVED** [review]

**Pull request merged**
